# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx485tffg1157-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Admin/Desktop/VERILOG/Lab_Work/B/Lab4/Q2/Synth/l4q2/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Admin/Desktop/VERILOG/Lab_Work/B/Lab4/Q2/Synth/l4q2/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/Admin/Desktop/VERILOG/Lab_Work/B/Lab4/Q2/Src/l4q2.v
catch { write_hwdef -file dff2.hwdef }
synth_design -top dff2 -part xc7vx485tffg1157-1
write_checkpoint -noxdef dff2.dcp
catch { report_utilization -file dff2_utilization_synth.rpt -pb dff2_utilization_synth.pb }
